# Generated by Django 5.2.7 on 2025-10-26 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tiempo', models.DateTimeField(verbose_name='Fecha y hora')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Imagen')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('plazas_totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de plazas')),
                ('plazas_disponibles', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Plazas disponibles')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['tiempo'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(related_name='eventos_asistidos', through='core.Registro', to=settings.AUTH_USER_MODEL),
        ),
    ]
